### ISSUE TITLE
0.6.0 TODO list.

### ISSUE THREAD

**Issue by CYBERDEViLNL** [marekjm/diaspy#41]
Here is what needs to be done before releasing 0.6.0. Discussion is possible, if you have a comment/suggestion please leave a message. I will be working on this, any help is appreciated :-)

**Edit:** For those who are watching, the changes I make are pushed to the `devel` branch for now. If all items are adressed we will merge it into the `master` branch.

#### Replace regex with BS4 where possible, but keep stdlib as fallback.
- [x] ~~`diaspy/connection.py`~~ regex here is used for script, BS4 can't do that.
- [x] `diaspy/models.py`
- [x] ~~`diaspy/people.py`~~ regex here is used for script, BS4 can't do that.
- [x] `diaspy/settings.py`

#### Make conversations possible.
- [x] Have working code with BS4, needs testing.
- [x] Regex fallback for the BS4 implementation.

#### Replace indentation from spaces to tabs in `tests.py`.
- [x] Done.

#### Update dependencies (`dateutil` or `pytz`, `bs4`(*optional*)).
- [x] `README.md`.
- [x] `setup.py` (extras_require).
- [x] Create `optional-requirements.txt`.
- [x] `requirements.txt`.

#### Check manual and update where needed.
- [x] `manual/connection.markdown`
- [x] `manual/models.markdown`
- [x] `manual/notifications.markdown`
- [x] `manual/people.markdown`
- [x] `manual/posting.markdown`
- [x] `manual/search.markdown`
- [x] `manual/streams.markdown`

#### Update infile version.
- [x] `docs/source/conf.py`
- [x] `diaspy/__init__.py`
- [x] `setup.py`

#### Testing
- [x] See if `tests.py` still succeeds.
- [x] User testing.

#### Update changelog.
- [x] v0.6.0.

**Comment by marekjm** [comment]
@CYBERDEViLNL Wow. You did a great job with release! Be sure to post about it on D\*!

**Comment by CYBERDEViLNL** [comment]
Thank you, I'll sure will :-)
